### ISSUE TITLE
Read/Write

### ISSUE THREAD

**Issue by GreenCame** [RealSpeaker/telegraf-session-local#10]
Hi, thanks for your work !

I have a problem with the local file in Debian, nothing is written inside except `{"sessions" : []}`
I don't get it because I work in my telegram bot on Windows 10 and everything work great ! But when I push my code to my Debian server, it doesn't work. 

The rights (permission) file was (rw-r--r--). I decided to change it : 

I try to set default permission to parent folder : [thanks to this link](https://unix.stackexchange.com/questions/1314/how-to-set-default-file-permissions-for-all-folders-files-in-a-directory). I have all rights (rw-rw-rw) but I have still the same issue.

Any idea ? Thanks ! 

(sorry for my english)

**Comment by TemaSM** [comment]
Hi, thanks for posting Issue with detailed info, appreciate it!

Right now I don't have access to my dev laptop & cannot test out package on Debian & Debian-like distros.
About 11-13 of October I will be back from abroad and will test everything about you wrote, for sure.
But one strange thing is that TravisCI reports about successfully passing tests by running on Ubuntu 14.04.5 LTS (Kernel 4.4.0-83-generic) with sudo (not sure)

Anyway I will reply to you, so please wait till 13 of October 😉

**Comment by GreenCame** [comment]
Ok, Thanks for your answer !

I dug and I understood, I think. When I try in windows 10 it was in private chat with myself, but when I push on debian it was for my group chat (I didn't test in private chat). So, if I don't post the command "/start" the session will not start. In case of group chat, the command start is not automatic. (It's not pratical)

I don't know if it's that, but it's solve my problem.
