### ISSUE TITLE
Typo in the full example

### ISSUE THREAD

**Issue by Taoufik-B** [RealSpeaker/telegraf-session-local#152]
Hello,

Thank you for sharing this project, it really helps me out.

I think there is a small typo in the documentation and examples regarding the full example.
When you have used the property 'data', it seems that it has been forgotten to be updated on [extra.js](https://github.com/RealSpeaker/telegraf-session-local/blob/master/examples/extra.js)file, on the following lines:
13. property: 'session', rather using only **property**,
38. ctx.session.counter, rather ctx[**property**].counter.

Thank you again.
Taoufik

**Comment by EdJoPaTo** [comment]
Looks like you are right. Wanna provide a Pull Request changing that?

**Comment by TemaSM** [comment]
@Taoufik-B thanks for catch!
What about line 13:
https://github.com/RealSpeaker/telegraf-session-local/blob/5a6e0a88c077373580638b30f298bced5e4a52ad/examples/extra.js#L13
\- it's correct, because we're overriding `property` field of `LocalSession` class instance, when calling `middleware()`:
https://github.com/RealSpeaker/telegraf-session-local/blob/5a6e0a88c077373580638b30f298bced5e4a52ad/examples/extra.js#L33
Gonna fix line 38 right now 👌

**Comment by TemaSM** [comment]
Fixed in https://github.com/RealSpeaker/telegraf-session-local/commit/a921e1506dd0abd81085dd2dc6d68c9c85ec0167

**Comment by EdJoPaTo** [comment]
> @Taoufik-B thanks for catch!
> What about line 13:
> 
> https://github.com/RealSpeaker/telegraf-session-local/blob/5a6e0a88c077373580638b30f298bced5e4a52ad/examples/extra.js#L13
> 
> - it's correct, because we're overriding `property` field of `LocalSession` class instance, when calling `middleware()`:
> 
> https://github.com/RealSpeaker/telegraf-session-local/blob/5a6e0a88c077373580638b30f298bced5e4a52ad/examples/extra.js#L33
> 
> Gonna fix line 38 right now ok_hand

I would avoid to use the line 33 way of doing as the config also specifies that property. It was misleading for @Taoufik-B and for me. Maybe it works but the example should provide a clear way of doing something.

**Comment by TemaSM** [comment]
Thanks for feedback. Seems to be it's really misleading.
Will deprecate argument of `.middleware()` in next version and remove it from docs and examples completely.
