### ISSUE TITLE
How to use this session local with Scene

### ISSUE THREAD

**Issue by zain-ul-abideen-ca** [RealSpeaker/telegraf-session-local#153]
I'm currently working on Scene and old session system of telegraf is deprecated so can you tell me how to utilize this library with scene.

**Comment by EdJoPaTo** [comment]
I am not familiar with the scenes of telegraf but the session of telegraf (which is deprecated) and this library are doing basically the same on the bot side of things. Just the location of the data is different (basically memory vs disk).

The reason for the deprecation of the session are race conditions. This library also has them so if you are avoiding the telegraf builtin session for the reason of its deprecation you should also avoid this library.
Check for more details on this deprecation in https://github.com/telegraf/telegraf/issues/1372.

Personally I still use this library and the built in session. You just have to know its limits.

**Comment by TemaSM** [comment]
Thanks for help @EdJoPaTo 👍
Closing now as stale, but if someone wanna ask more - feel free to do so.
