### ISSUE TITLE
Is it possible to change a user session?

### ISSUE THREAD

**Issue by Spring7331** [RealSpeaker/telegraf-session-local#207]
Hi im trying to change a users session, like lets say they have abc = 1 for Mr A. Im Mr B. I want to change Mr A abc to 2.

**Comment by EdJoPaTo** [comment]
The idea behind sessions is to keep some state for the current user without needing to care about its userID, chatID or stuff like that. So the sessions are designed to not care about the identification which would be needed to access Mr. A or Mr. B.

So yeah, you can use the `getSession` function with the key generated by your `getSessionKey` function for the user you want to change but its not what sessions are intended to do for.
It is probably a better idea to create a separate store for data which is accessed and changed by multiple users.

**Comment by TemaSM** [comment]
Thanks for help @EdJoPaTo 👍
Closing now as stale, but if someone wanna ask more - feel free to do so.
