### ISSUE TITLE
How many concurrent users this library can handle?

### ISSUE THREAD

**Issue by lukahukur** [RealSpeaker/telegraf-session-local#241]
I would be glad to get an answer

**Comment by TemaSM** [comment]
Hi
I haven't done any benchmarks.
In general, considering that under the hood sessions are stored in files, and all operations occur at the disk I/O level, we can assume that this option is definitely worse for production use than a specially designed for such purposes databases, for example: KeyDB (Redis), Postgres/MySQL/MariaDB, MongoDB, etc.

**Comment by tailsjs** [comment]
LowDB can handle many sessions, but it's json database. So, it means if you gonna update db quite often, it may break

**Comment by TemaSM** [comment]
@tailsjs thanks for the addendum.

I hope we've answered the question posed, so I'm closing this issue.
