### ISSUE TITLE
session is not saved inside Promise.then

### ISSUE THREAD

**Issue by crystalbit** [RealSpeaker/telegraf-session-local#26]
Hi.
Example:
`getSources().then(src => {ctx.session.sources = src});`
just modifies the session and doesn't save it, while 
`ctx.session.sources = "test";`
modifies and saves the session.

First example gets the session, modifies it - we can check it there by console.log for example. But it doesn't affect the database file.
The same issue using async/await:
`ctx.session.sources = await getSources()`
and all the code above modifies session, but it isn't saved

**Comment by crystalbit** [comment]
problem has gone after I used bluebird in my project.
but I think issue with standard promises is still actual

**Comment by TemaSM** [comment]
@crystalbit Hi there!
Thanks for information, I will make some tests to reproduce this issue.
What versions of npm and Node.js are you using?

**Comment by crystalbit** [comment]
Hi!
node 10.12.0
npm 6.4.1

**Comment by TemaSM** [comment]
Seems to be, that this problem fixed in 410b7403bf0f4f83901eebf300ca093b80ed0455
So, closing now.
