### ISSUE TITLE
Save a session on bot start?

### ISSUE THREAD

**Issue by amirhoseinsalimi** [RealSpeaker/telegraf-session-local#49]
Hello,

I want to save user's information as he/she starts using my bot but I figured out setting sessions on `bot.start()` doesn't work or at least I'm doing something wrong. Manipulating sessions on other event handlers (`.hears()`, `on('audio')`, etc.) works well though.
Here's the code:

![Screenshot from 2019-08-16 15-33-26](https://user-images.githubusercontent.com/25503371/63163659-47b29480-c03b-11e9-8f46-3a223c5ff648.png)

Where did I go wrong? Is this a Telegram bot API limitation?

**Comment by TemaSM** [comment]
Hi,
I tried to reproduce, but it worked well, just as expected.
May you please give info about `Telegraf` and `telegraf-session-local` versions you're using?
Also, it would be great if you send me a link to repository or attach zipped sources of you bot. (with `package.json` but without `node_modules`)

**Comment by amirhoseinsalimi** [comment]
Sorry for my late reply and thank you for your attention.

After 3 days it's turned out that moving the session-related statements to the upper scope (outside `if... else`) solves the problem! Also, a funny mistake I had made was to miss parenthesis to invoke the constructor of date -> `new Date` (line 49). Now the code looks like this and works as it should does:

![Screenshot from 2019-08-19 23-59-06](https://user-images.githubusercontent.com/25503371/63293878-43f26c80-c2de-11e9-9946-f3eeedfc779f.png)

**Comment by TemaSM** [comment]
Nice to hear that you solved the problem 👍 
Now closing this "issue", but feel free to re/open if you have any questions or facing bugs in `telegraf-session-local`
