### ISSUE TITLE
Property 'session' does not exist on type 'TelegrafContext'

### ISSUE THREAD

**Issue by negebauer** [RealSpeaker/telegraf-session-local#83]
Hi, I'm new to typescript and I'm working on a Telegraf bot using this library.

I have the following code

```ts
import { Telegraf } from 'telegraf'
import LocalSession from 'telegraf-session-local'
import config from './config'

const bot = new Telegraf(config.botToken)
const session = new LocalSession({ database: 'db.json' })

bot.use(session.middleware())

bot.on('text', (ctx, next) => {
  ctx.session.counter = ctx.session.counter || 0
  // eslint-disable-next-line no-plusplus
  ctx.session.counter++
  ctx.replyWithMarkdown(
    `Counter updated, new value: \`${ctx.session.counter}\``,
  )
  return next()
})

bot.launch().then(() => {
  // eslint-disable-next-line no-console
  console.log('Bot started successfully')
})
```

which shows a typescript error `Property 'session' does not exist on type 'TelegrafContext'`

How can I let typescript now that `session` is added by the library and give it the correct type?

**Comment by EdJoPaTo** [comment]
first you need to type your own Session:

```ts
export interface MySession {
  counter?: number;
}
```

Then you can extend it onto the existing context

```ts
import {Context as TelegrafContext} from 'telegraf'
export interface MyContext extends TelegrafContext {
  session: MySession;
}
```

Which you then use for your bot:

```ts
import {Telegraf} from 'telegraf'
const bot = new Telegraf<MyContext>(token)
```

all methods on bot like bot.on will then use your MyContext and thus MySession.

There is a full working example at my [typescript bot template](https://github.com/EdJoPaTo/telegram-typescript-bot-template/blob/master/source/bot/my-context.ts).
Hope it helps :)

**Comment by negebauer** [comment]
Thanks a lot, that's exactly what I needed.
